### ISSUE TITLE
completely desaturates the world

### ISSUE THREAD

**Issue by Lemente** [t-affeldt/regional_weather#10] opened 2023-05-15 12:30 UTC
When using this mod and with shaders activated (MTG weather off), the world is almost completely desaturated.
more info :
- MTG game
- Minetest 5.7 on windows 10
- only the Regional Weather Bundle installed

![screenshot_20230514_205004](https://github.com/t-affeldt/regional_weather/assets/27686967/34e3cda0-8be7-4a5b-8ef6-4b0df81383c9)

doing "/set_weather regional_weather:ambient off" solves the issue, but I assume it also removes some of the mod features.
![screenshot_20230514_210352](https://github.com/t-affeldt/regional_weather/assets/27686967/65b14289-949f-4b3b-bfc5-37762b089a1e)

**Comment by APercy** [comment] 2023-10-31 00:06
To fix it, change the function map_range at file "regional_weather/ca_weathers/ambient.lua", line 15, to this:
`

	-- maps range of 0 to 1 to any other range
	local function map_range(val, low, high)
		local cal_val = math.min(math.max(val, 0), 1)
		local range = high - low
		return low + (cal_val * range)
	end

`

**Comment by t-affeldt** [comment] 2024-07-06 17:12
Hello! Sorry for the late reply as I don't have time for modding and as such, cannot offer much support.

This bug is the cause of a misconfigured feature.
I implemented it when shaders were still under development and then didn't correct for changes to them when they were officially released.

It is supposed to simulate diffused lighting conditions under overcast weather.
Unfortunately, the values are set way too extreme, so that it appears either way too desaturated or way too saturated.
I hadn't felt a need to make them configurable, so there is no easy way to fix it without changing something in the code.
You can **disable tone maps** in your Minetest settings to disable the feature but it might affect other visual aspects.

For those willing to change two lines of code, you can tweak the values in [ambient.lua](https://github.com/t-affeldt/regional_weather/blob/master/ca_weathers/ambient.lua) to your liking (lines 30 and 37). More info on my [forum post](https://forum.minetest.net/viewtopic.php?p=437354#p437354). I am willing to accept push requests if they come with screenshots.

**Comment by t-affeldt** [comment] 2024-09-26 23:16
This is now fixed in the latest version. :)

**Closed by t-affeldt** 2024-09-26 23:16 UTC
Labels: bug, help wanted
